#!/bin/bash

# Create virtual environment
virtualenv .venv --python=python3

# Activate virtual environment
source .venv/Scripts/activate

# Install required packages
pip install -r requirements.txt

# Print completion message
echo "Installation completed!"